modules/angular-meteor-collections.js

If you want to pass ```options```, then your ```bindOne``` will look like ```$collection(Todos, null, { fields: { content: 1 } }).bindOne($scope, 'model', criteria)```.
I tested that if ```options``` is ```undefined``` the ```findOne``` will still work.

Use options on findOne of bindOne

---

modules/angular-meteor-collections.js

Hey @Urigo, The 'angular-meteor.collections' module has a dependency on the 'hashKeyCopier' module. See: line 148. 
If you work with this module independently, Angular.js throws an exception.
Thanks!
Yago

Fixed: dependency problem in angular-meteor.collections

---

modules/angular-meteor-meteorCollection.js

Continuing #163 with a pull request on a different branch.
Here I've moved the object diff logic into `diffArray` and also made sure that the diff function recognizes when keys are removed from the model. When they are, an `{$unset: {}}` modifier is used in `collection.save()`.

Diff changes to Angular model before updating Meteor collection

---

plugin/handler.js

As discussed in #169, we need to normalize paths across platforms to be able to consistently refer to templates in apps.
There might come a [standardized solution](https://github.com/meteor/windows-preview/issues/47), but this is so simple, it could be used in the meantime.

Convert Windows style paths to *nix style in build step

---

plugin/handler.js

Since a standardized solution to our problem might arrive at a later time, we want to include some details about that in the code. See #169

Added comment about replacing backslashes in compile step

---

.docs/angular-meteor/client/views/api/api.user.html
modules/angular-meteor-user.js

issue #181
@Urigo, this is my first pull request, so please review my changes. Now it should be sufficient to just set in your route config:
```javascript
$stateProvider
.state('home', {
url: '/',
templateUrl: 'client/views/home.tpl',
controller: 'HomeController'
resolve: {
currentUser: $rootScope.currentUserPromise
}
});
```
Or if you don't want to hide the reactive $rootScope.currentUser in yout controller's scope, just assign it to another property:
```javascript
$stateProvider
.state('home', {
url: '/',
templateUrl: 'client/views/home.tpl',
controller: 'HomeController'
resolve: {
currentUserNonReactive: $rootScope.currentUserPromise
}
});
```
It is also a good idea to maybe add the currentUserPromise to the unit tests.

Added currentUserPromise to the $rootScope

---

modules/angular-meteor-meteorCollection.js

Related to #195.
This should allow for transformed documents, but not only the collection transform but also cursor transform.
Also removed the need to find the index of changes by looking through the whole collection.
Not sure about it performace-wise.
@Urigo You have a good scenario for checking the performance of this vs observeChanges?

move to observe instead of observeChanges

---

plugin/handler.js

Removing all whitespace in templates (as is being done currently) can have side effects for how the content is presented when it comes to inline elements, eg.
```html
<p>My name is <em>Fredrik</em></p>
```
is compiled into
```html
<p>My name is<em>Fredrik</em></p>
```
Even though this does increase the filesize slightly, I think it definitely is expected behavior for this kind of inline space to be preserved all the way in to the browser.

Maintain a single whitespace between elements in compiled templates

---

plugin/handler.js

Angular directives can be included with [HTML comments](https://docs.angularjs.org/guide/directive#directive-types), so we want to preserve those in the minified templates.

Preserve comments in minified templates

---

.npm/plugin/ngAnnotate/.gitignore
.npm/plugin/ngAnnotate/README
.npm/plugin/ngAnnotate/npm-shrinkwrap.json
package.js
plugin/annotate.js

I know it's being discussed at https://github.com/Urigo/angular-meteor/issues/109 and https://github.com/meteor/meteor/issues/3508 but it looks like we have to wait until they find a way to process the original .js files.
So hence my PR as a suggestion: why for now not register `ng.js` to be processable by ng-annotate? It would make my project a lot easier to work with.
In addition, we could do more processing on this extension such as https://github.com/werk85/grunt-ng-constant.

feat(plugin): support for ng-annotate, process .ng.js files

---

plugin/handler.js

The issue was introduced in a47ecc2. When a ng.html file contains multi-line comments Meteor failed on the console with error like "Unexpected token ILLEGAL" due to the generated JS that adds the html to the template cache was broken.
For example this could break your app:
```
<div>
</div>
```
In order to properly fix that - the best future proof approach is to JSON.stringify the strings as this ensures any JS special character is properly escaped and turned into string literal.
@Urigo - this is real big issue with the latest version v0.8.0, so please act quickly

Fix problem with multi-line comments breaking compileAngularTemplates step due to invalid JS generated for the template

---

modules/angular-meteor-user.js

correct me if i'm wrong, but i believe a bunch of those methods use Accounts, not Meteor. I was getting:
'''undefined is not a function
TypeError: undefined is not a function
at angularMeteorUser.service.createUser (http://localhost:3000/packages/urigo_angular.js?4b36953210173c874060f2e4feb315d53f8eca68:1562:14)'''

Accounts not Meteor for a few methods

---

README.md

Added a reference in README to the new package pbastowski:angular-babel. JavaScript files ending in .es6 will first be transpiled by Babel and then annotated with ng-annotate. Without this package angular-meteor will only ng-annotate files that end in .ng.js.

add pbastowski:angular-babel

---

plugin/handler.js

***BREAKING CHANGE*** templateUrl paths for *.ng.html files inside meteor packages have been changed.
angular-meteor now prefixes the package name when adding templates to $templateCache. The colon in the package name is replaced with an underscore and the package name is separated from the template name with an underscore. So, if you have a package named my-app:my-package with a template at packages/my-app:my-template/client/views/my-template.ng.html, the templateUrl you use in the route should be:
my-app_my-package_client/views/my-template.ng.html

Fix #258 - Add compileStep.packageName to templateCache key

---

angular-meteor.js

After having tested my app, I decided that recent changes to the onAfterAction are too complex.
I propose to revert it back with once change: check it's been compiled only once. It's what regular Angular needs. Anything else is up to a developer. For example, one could create a separate Angular module with onAfterAction (or whatever) and write there any route changes handling (as I did).

Reverts back recent changes to the onAfterAction handler.

---

.docs/angular-meteor/client/views/api/api.auth.html
angular-meteor.js
modules/angular-meteor-user.js

Current behaviour: when using $meteor.requireUser(), a resolved promise will be returned if there is an authenticated user, and a rejection if not.
Proposed behaviour: allow $meteor.requireUser() to receive a function that will evaluate if the logged user has permission or not.
Usage:
The received function will be executed with the user object as the only paramenter. If the function returns a string, such string will be used to reject the resolution; otherwise it will resolve with the user as expected.
Example:
```javascript
$stateProvider.state('secure-page', {
url: '/my-top-secret-page',
templateUrl: 'my/top/secret/page.ng.html',
resolve: {
currentUser: ['$meteor', function($meteor) {
return $meteor.requireUser(function(user) {
if(!_.contains(user.roles, 'root')) {
return 'FORBIDDEN';
} …
```

Allow to use a checker function before resolving

---

modules/angular-meteor-meteorCollection.js

Hi, I had and object that contained a null value like this:
```
myCollection.save({foo: null})
```
which produced an error at ```delete prop.$$hashKey```

object check in $$hashKey deletion in nested values

---

.docs/angular-meteor/client/views/api/api.meteorCollection.html
.docs/angular-meteor/client/views/api/api.meteorObject.html
.docs/angular-meteor/client/views/api/api.subscribe.html
modules/angular-meteor-meteorCollection.js
modules/angular-meteor-object.js
modules/angular-meteor-subscribe.js

$scope subscribe, collection, and object methods prefixed with $meteor

---

modules/angular-meteor-utils.js

This is a very small change, it's just a wrapper of $meteor.autorun to be available as $scope.$meteorAutorun. This will allow to change this:
```javascript
// ....
.controller('MyController', ['$scope', '$meteor', function($scope, $meteor) {
$meteor.autorun($scope, function() {
// ......
});
}]);
```
for this:
```javascript
// ....
.controller('MyController', ['$scope', function($scope) {
$scope.$meteorAutorun(function() {
// ...
});
}]);
```
Before continuing on the PR to add docs, I would like to hear opinions on this. Should we continue to add $meteor stuff to $rootScope? Is it a good idea to have these methods always available?
$scope.$meteorSubscribe, $scope.$meteorCollection, & $scope.$meteorObject are wrappers that add extra functionality that depends on $scope ($on('$destroy')), …

$scope.$meteorAutorun wrapper to simplify usage

---

modules/angular-meteor-meteorCollection.js
modules/angular-meteor-utils.js
tests/integration/angular-meteor-utils-spec.js

A common use case is that you insert FS.File instances in a cfs collection, the strip hash key function ignored this case and returns a object. This results in an error if you do something like
```
var fsFile = new FS.File(file)
fsFile.ownerId = Meteor.userId();
MyCollectionFS.insert(fsFile);
```
I added the handling of FS.File to the strip function

Cfs file insert fix

---

modules/angular-meteor-reactive-scope.js
package.js
tests/integration/angular-meteor-reactive-scope-spec.js

Hi,
I added a method to scope that to support angular $watchCollection as it should provide a more performant way if you want to react on array changes in terms of pushes etc than using ```$scope.getReactively("myValues", true)``` way

added getCollectionReactively to scope

---

.docs/angular-meteor/client/views/steps/tutorial.step_06.html

Buttons should not contain any interactive descendants.
"<button><a href="/parties">Cancel</a></button>" is invalid in HTML5.
This doesn't work in Firefox 38.
Reference: https://stackoverflow.com/questions/2906582/how-to-create-an-html-button-that-acts-like-a-link

Fix cancel button syntax problem.

---

lib/diff-array.js
tests/integration/angular-meteor-collection-spec.js

Several different combinations of "new-field-type" and "previous-field-type" led to broken behavior on meteorCollection. Having null as a previous value on a field, for instance, could break if the field was both at a shallow or a deep position in the object. Big problem is the real collection data is updated and persisted, but the angular collection sync code would raise a TypeError some time after that, and potentially affect angular execution. 
This PR assures good behavior on the scenarios described by the added tests, but the sad reality is that dealing with object-diff and read-write of deep fields is challenging. I think we should consider bringing pieces of more stable code into angular-meteor in order to improve diff-array.js. 
For example, lodash ```_.get```, ```_.set``` and …

Fix meteorCollection bad behavior with deep-objects update and null fields

---

modules/angular-meteor-object.js
package.js
tests/integration/angular-meteor-object-spec.js

I didn't use deepCopyChanges and deepCopyRemovals, because I wasn't able to copy only the changes / removals without the client (user and internals) properties.
* AngularMeteorObject.reset(): Add `keepClientProps` argument to remove only
server side removed properties, in compare when called by the user that
will remove all properties.
* AngularMeteorObject: Add _serverBackup - to be able to detect between
server unset properties and client only properties.
* AngularMeteorObject: Add tests

fix(AngularMeteorObject): delete server properties after unset changes

---

.docs/angular-meteor/client/views/steps/tutorial.step_02.html

Just fixing a couple spelling errors. :) First pull request on Github.

Fix tutorial 2 spelling errors: 'braches' to 'braces'

---

modules/angular-meteor-session.js
tests/integration/angular-meteor-session-spec.js

MeteorSession doesn't work with nested mode something link 'a.b.c'
Fix it by using angular $parse

Use angular $parse to handle nested mode (a.b.value)

---

modules/angular-meteor-collection.js
modules/angular-meteor-object.js
tests/integration/angular-meteor-object-spec.js

The tracker will do so by observing any changes made on the Meteor.Collection, thus unnecessary deep changes copy was removed

Remove unnecessary local update

---

modules/angular-meteor-collection.js
package.js
tests/integration/angular-meteor-collection-spec.js

Main purpose is to clearly separate server update logic from the client one.
So that we don’t have any special variable that sets mode globally (like "UPDATING_FROM_SERVER")
For each update from the server or any internal changes to the collection, we perform
_unsetAutoClientSave
… here changes go
_setAutoClientSave
Also ````collectionUtils```` has been changed to provide collection with the changes only,
saving of the changes collection take care of by itself from now own, which simplified code flow.
All Tracker.Autotuns now are stopped on the collection’s stop method as well.
Also, I seem to have understood the reason of https://github.com/meteor/simple-todos-angular/issues/2.
It was very likely due to uncontrollable ````setAutoBind````, which may have run
multiple time here …

One more pass of meteorCollection re-factoring.

---

.docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_02.md
.docs/angular-meteor/client/stylesheets/content/angular-2.import.less
.docs/angular-meteor/client/stylesheets/content/api_tutorial/common.import.less
.docs/angular-meteor/client/stylesheets/home/home.import.less
.docs/angular-meteor/client/stylesheets/main.less

* Gave paragraphs in the tutorials some more breathing room
* Added list-style back in, it was missing and made some parts of the tutorial look weird (basically ignoring all markdown lists)
* fixed paddings / margins on the home page.

Spacing on tutorials, fix spacing on home, show lists

---

lib/diff-array.js
package.js

Since commit meteor/meteor@b3096e93, MongoId and the _idStringify
(or _idParse) method is in a separate package.
diffArray currently assumes the _idStringify and _idParse methods to
be in LocalCollection, but this isn't true anymore in recent versions
of Meteor. Therefore, diffArray() throws an error on (for example)
Meteor 1.2.
This commit fixes this issue by using the mongo-id package if we cannot
find LocalCollection._idStringify and LocalCollection._idParse are
undefined.

Fix idStringify for recent versions of Meteor

---

modules/angular-meteor-collection.js

Fix a wrong variable being used in the movedTo() observe function.
This fixes a regression introduced by a recent refactor (commit 88b50bf).

Collection: Fix wrong variable in movedTo()

---

.docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_12.md

@Urigo 
Fixed this:
https://github.com/Urigo/meteor-angular-socially/commit/a00ab08e3e953f91d23097ca23baf4b80c2417fe#commitcomment-12981461

Update Step 12 and updated the note in the pagination tutorial

---

plugin/handler.js

It should be a reference to the user's meteor developer account name, no?

changed prefix in comment

---

package.js

@Urigo check this out. I've added dependencies to the on_use and to the on_test. we need them for both, cause without this packages our package can't work. It used to always work because of meteor-platform, but now if someone doesn't use all of the packages we need it might break. This should fix it..

added missing dependencies for meteor 1.2 in tests.

---

.docs/angular-meteor/client/content/api/api.subscribe.html
modules/angular-meteor-subscribe.js
package.js
tests/integration/angular-meteor-subscribe-spec.js

* User supplied onStop will be called after subscription is already active and was stopped by an error or call to stop method.
* This does not break the stable API of meteorSubscribe and and adds a way to be notified on an event of subscription stopping after it was resolved.
* Added tests for meteorSubscribe service.
* This PR also removes deprecated argument of Meteor.subscribe. https://github.com/meteor/meteor/blob/master/packages/ddp-client/livedata_connection.js#L466-L496
* Meteor docs quote describing onStop: "The onStop callback is called with a Meteor.Error if the subscription fails or is terminated by the server. If the subscription is stopped by calling stop on the subscription handle or inside the publication, onStop is called with no arguments."

(meteorSubscribe) Added options object argument with a user supplied onStop callback 

---

.docs/angular-meteor/client/content/patches/angular2-meteor.multi.patch

Fix for [this issue](https://github.com/ShMcK/ng2-socially-tutorial/commit/062f352bd8867e3627802df5d009f1bcf9de9093#commitcomment-13702054).
The `templateUrl` was pointing to an invalid moved template.
Note: the tutorial is still broken and requires an update using `urigo:meteor-angular2`.

update app.ts template to point to <router-outlet>

---

modules/angular-meteor-utils.js

Meteor collections currently require that _id be either a string or the EJSON
version of Mongo's ObjectID. When documents are being saved with ObjectID (such
as in early steps of the current angular tutorial on meteor.com), the
`stripDollarPrefixedKeys` method that is called by the `_upsertDoc` method of
`AngularMeteorCollection` causes ObjectIDs to be converted into POJOs, which
causes Meteor to throw errors about their data types and messes everything up.
This commit causes values with EJSON type 'oid' (such as the server-side
ObjectIDs) to pass through `stripDollarPrefixedKeys` without modification.

Fix ObjectID being converted to Object during updates

---

lib/diff-array.js
tests/integration/angular-meteor-diff-array-spec.js

Originaly created to fix [this](https://github.com/roeeyud/angular-meteor-watching-array-bug) issue.

Splice removed elements from an array on diffArray.deepCopyRemovals()

---

.docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_00.md
.docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_02.md
.docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_03.md

Step 0 - Bootstrapping
After the first run, you will find tge -> After the first run, you will find the
Step 2 - Dynamic Template
"party of parties" -> "#party of parties"
Step 3 - 3-Way data binding
that should happen reactively happen reactively -> that should happen reactively.
Remove lines "Now every change what happens to the this.parties variable should automatically be saved to the local client-side minimongo DB and synced to the server-side MongoDB and all the other clients in realtime!". If I understand right the changes from minimongo will affect this.parties but changes in this.parties will not affect data in minimongo.

fix typos in angular2 tutorial in steps 0, 2, 3

---

bower.json

The `main` field in bower.json refers to a non-existent directory. This prevents tools like [main-bower-files](https://www.npmjs.com/package/main-bower-files) from working correctly. This PR fixes that field to point to the main script in the `dist/` directory.

Fix "main" path in bower.json

---

docs/angular-meteor/packages/tutorial-step-diff-compiler/.npm_old/plugin/mdg:tutorial-step-diffs-plugin/.gitignore
docs/angular-meteor/packages/tutorial-step-diff-compiler/.npm_old/plugin/mdg:tutorial-step-diffs-plugin/README
docs/angular-meteor/packages/tutorial-step-diff-compiler/.npm_old/plugin/mdg:tutorial-step-diffs-plugin/npm-shrinkwrap.json
packages/angular-templates/plugin/ng-caching-html-compiler.js

Fixes https://github.com/Urigo/angular-meteor/issues/888
Note that I can't seem to clone or commit without deleting these files in `.npm_old`, git gives me all kinds of erros.

Include file path in the cache key of NgCachingHtmlCompiler

---

packages/angular-with-blaze/package.js

replaces Urigo/angular-blaze-template#8
should also fix Urigo/angular-blaze-template#10

Adding blaze-html-templates as a dependency to angular-with-blaze

---

packages/angular-meteor-data/modules/angular-meteor-reactive-context.js
packages/angular-meteor-data/modules/angular-meteor-reactive-scope.js
packages/angular-meteor-data/tests/integration/angular-meteor-reactive-context.spec.js
packages/angular-meteor-data/tests/integration/angular-meteor-reactive-scope.spec.js

@Urigo 
Fixed in order to provide this logic:
```js
class myComponent {
constructor() {
this.subscribe('name', this.fn); // now the call to that fn will be with the correct context 
}
fn() {
return [10, 20, 30];
}
}
```

(bugfix) Fix subscription call, used apply with the context

---

docs/angular-meteor/client/layout/navbar.html

angular-meteor have been updated and the first place I go to for read about the update is the obvious "Blog" menu on the top then I found it isn't up to date. So I think you should change "Blog" url as my suggestion or up date your medium blog.
What do you think?

I though medium blog is not up to date enough!

---

README.md
docs/angular-meteor/client/content/tutorials/socially/angular1/tutorials.socially.angular1.step_14.md

To eliminate frustration for new visitors, fixed the angular-meteor.com urls to point to http instead of https. The https calls are not resolving.

changed anguluar-meteor.com urls to use http since https not supported

---

docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_11.md

The meteor `install-sdk command` no longer attempts to download and install the tools for you (it has been deprecated and just points you to these instructions).

The meteor install-sdk command no longer works

---

docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_00.md
docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_07.md
docs/angular-meteor/client/content/tutorials/socially/patches/meteor-angular2-socially.multi.patch

Since declaration files are contained in own folders now,
Angular 2 Tutorial was changed accordingly.
Fixes https://github.com/Urigo/meteor-angular2.0-socially/issues/40
Add some other minor fixes.
Deployed - ng2-tutorial.meteor.com

Angular 2 Updates

---

package.json

@Urigo You're asking me about it, here's simple solution :)
You don't have to run `npm run build` on every time you want to publish new release.

chore(npm): build before publish

---

package.json

Closes #1210 
To generate the changelog of the new release, you have to run:
```
npm run changelog
```
I could make that changelog would be generated right before publishing new version but I think it's better to run it manually so you can check everything.
---
To create a whole new changelog, including very previous changes, use:
```
conventional-changelog -p angular -i CHANGELOG.md -s -r 0
```

chore(changelog): auto-changelog generator

---

package.json
src/angular-meteor.js
webpack/common.js

It can be used like that:
```javascript
import angular from 'angular';
import angularMeteor from 'angular-meteor';
angular.module('app', [
angularMeteor
]);
```

commonjs support for es6 modules

---

tests/integration/reactive.spec.js

test(reactive): helpers should not invoke on observation update

---

src/lib/diff-array.js
src/lib/get-updates.js
src/lib/underscore.js
src/modules/angular-meteor-collection.js
src/modules/angular-meteor-methods.js
src/modules/angular-meteor-object.js
src/modules/angular-meteor-user.js
src/modules/angular-meteor-utils.js
src/modules/core.js
src/modules/mixer.js
src/modules/reactive.js
src/modules/utils.js
src/modules/view-model.js
webpack/common.js

**Before**:
We were using global `_` variable so it might be causing few errors when there is no `underscore` package in meteor app.
**Now**:
We're importing `underscore` instead of using global object.
I made webpack to be compatible with global variables (`root`), amd, commonjs2 and commonjs.
```javascript
underscore: {
root: '_', // this looks for underscore in global window object
amd: 'underscore',
commonjs2: 'underscore',
commonjs: 'underscore'
},
```
But `underscore` in meteor world is not a global variable but it's under package scope as local variable.
I had to fix it somehow, you can check it  in `src/lib/underscore.js`.
@Urigo

chore: use underscore dependency

---

.github/CONTRIBUTING.md
package.json
webpack/dev.js

`npm link` and `npm run watch` is amazing to use :smiley:
Cotributor won't have to recompile `angular-meteor` or rerun meteor app.
The same thing with symlink and `npm run watch:dev` in Meteor 1.2.
---
Closes: #1288

Update docs: running locally

---

packages/angular-meteor-data/package.js

before:
```javascript
var require = meteorInstall({"node_modules":{"meteor":{"angular-meteor-data":{"angular-meteor.js":function(require,exports,module){
/*! angular-meteor v1.3.9 */
(function webpackUniversalModuleDefinition(root, factory) {
if(typeof exports === 'object' && typeof module === 'object')
module.exports = factory(require("underscore"), require("jsondiffpatch"));
else if(typeof define === 'function' && define.amd)
define(["underscore", "jsondiffpatch"], factory);
else if(typeof exports === 'object')
exports["angularMeteor"] = factory(require("underscore"), require("jsondiffpatch"));
else
root["angularMeteor"] = factory(root["_"], root["jsondiffpatch"]);
})
// ...
```
after:
```javascript
(function(){
/*! angular-meteor v1.3.9 */
(function …
```

chore(angular-meteor-data): use node module without ecmascript

---

src/modules/core.js
tests/integration/core.spec.js

Once a computation has been stopped the destroy event listener will be removed
to avoid memory leaks and unexpected behaviors

fix(autorun): destroy event listener once autorun has been stopped

---

bundle-min.sh

As for now the Bower version of angular-meteor does not work due to package dependencies problem. This PR fixes it.

chore(bundle): Add modules package to bundle script

---

src/modules/core.js
tests/integration/core.spec.js

@Urigo 
Related to #1092 
---
```js
this.subscribe('books', () => [ this.getReactively('published') ], {
onStart() {}, // new callback
onReady() {},
onStop() {}
});
```
---
I used object as a hook container instead of a single variable for `onStart`, so we'll be ready to add new hooks. 
Let's say we want to create `beforeStart` and `afterStart`, it's now a two lines thing.

feat(Core): onStart callback

---

packages/angular-templates/templates-handler.js

`$angularTemplatesSettings` constant as a plain object with two properties:
- `(boolean) error` - throws an error - *default: true*
- `(boolean) warning` - uses console.warn - *default: true*
Of course `error` overwrites `console.warn`.
If someone wants to avoid throwing errors he can simply set `error` to false and still he will see helpful warnings about missing template.
In different case, when user doesn't want to be notified, he can set both options to false.

feat(templates): optional error and warning of missing template

---

packages/angular-templates-runtime/ng-template-compiler.js

```js
#
#
// before
import templateUrl from './template.html';
// after
import { templateUrl } from './template.html';
```
---
Restored previous behavior to export templateUrl by default and added space for additional variables.

refactor(templates): use exports.default with __esModule

---

renovate.json

Meteor renovation is now enabled by default, so it is no longer necessary to explicitly enable meteor.

chore(renovate): remove unnecessary meteor enablement

---

run_tests.sh

Travis was actually broken since we moved all the commands in a separate script (`run_tests.sh`), such a way the exit codes from mocha were actually hidden behind the bash script and Travis couldn't manage to pick them up. I made them propagate up to Travis.
Because of this we didn't notice that tests did actually break despite the "green flag" from Travis.
To fix them please merge https://github.com/Urigo/angular-meteor/pull/1706 together with this commit.

Fix tests exit codes for CI

---

atmosphere-packages/angular-typescript-compiler/index.js

Condition was added for defining is tsconfig.json from project and not from node_modules, case when user install some package directly from github repository

Fix reading of settings from tsconfig.json

---

examples/angularcli-meteor/package.json

This change will ensure that the `angularcli-meteor` example receives separate Renovate PRs from the other `package.json` files in the repository. Instead of the usual `renovate/` prefix, updates to this file will be given a `renovate/angularcli-` prefix to differentiate them, as discussed in the comments of #1732

chore: set custom renovate branch prefix for angularcli example

---

examples/AngularCLI/README.md

Followed commands and symlinks weren't working because thought it would work with entering `api/`

Update commands on README.md

---

atmosphere-packages/angular-typescript-compiler/index.js

Currently there is no support for namedExports when using the Rollup plugin which generates an unusable build when a 3rd party package is required and not resolved during the compilation. With this change we can allow the user to define a file called 'named-exports.json' at the root of the project and define all the namedExports required in the code.
This file could contain something like this:
```
{ './module.js': ['foo', 'bar' ] }
```
If the file does not exist, the rollup method will be passed the null value as is the current behavior.

Add support for namedExports when using Rollup plugin

---

atmosphere-packages/angular-compilers/package.js

This is a quick fix to pin the required atmosphere packages to the most recent versions. Upgrade to Meteor 1.9 is otherwise not possible

Update compiler dependencies to most current versions
