Urigo/angular-meteor

- modules/angular-meteor-meteorCollection.js
- versions.json
refractor into factories for classes.
> fix issues related to auto bind

- modules/angular-meteor-object.js
After line 61 the variable 'auto' will aways be true/false
> Fixed: Unreachable exception. 

- README.md
I thought the README could use some updates, so I updated the following points:
- help for others to avoid the problem I mentioned in #134 with the separation of Meteor and Angular templates
- added short descriptions and code examples for every section under "Usage"
- added syntax highlighting to all code examples
- general formatting
- fixed a few typos
> Updates to README content and formatting

- .coveralls.yml
- .gitignore
- package.json
- test/karma.conf.js
> build: Adds support for coveralls

- README.md
> Docs: simplifies steps

- modules/angular-meteor-meteorCollection.js
As discussed in #165, here I've used recursion to diff nested documents, both for the `{$set}` and `{$unset}` diff.
The nested diff is constructed using dot notation for every key name. That means that every property that should be updated is made an immediate descendant of the modifier. Its name can contain dots however, in which case it will be resolved as a modifier of a nested document.
Example:
```js
{$set: {"name.firstName": "Fredrik"}}
```
```js
{$unset: {"name.middleName": true}}
```
> Use recursion to diff nested documents

- .docs/angular-meteor/client/views/steps/tutorial.step_08.html
The sentence on line 159  referenced parties-list.html which is wrong. It should reference parties-list.tpl.
> Update Tutorial step 8

- .docs/angular-meteor/client/views/steps/tutorial.step_15.tpl
Per https://github.com/Urigo/angular-meteor/issues/200
> Must be logged in template now hidden while authenicating

- angular-meteor.js
Fixes #154 issue (IronRouter runs sometimes runs onAfterAction twice which leads to double compilation).
http://ng-meteor-test.meteor.com is a deployed test app with this test fixed package added,
pls check logs there to verify fix.
> Fix of #154

- .docs/angular-meteor/client/styles/about/about.less
- .docs/angular-meteor/client/styles/main.less
- .docs/angular-meteor/client/styles/variables.less
- .docs/angular-meteor/client/views/about.html
- .docs/angular-meteor/client/views/tutorial.html
> Refactor some Less, more style to About, respond to feedback on Tutorial

- modules/angular-meteor-object.js
- test/angular/unit/angular-meteor-object.Spec.js
* Added a method to AngularMeteorObject that returns a copy of the object without any of the internalprops.
* Fixes #247
> Create a raw object getter.

- .docs/angular-meteor/client/views/api/api.AngularMeteorObject.html
* Document the .getRawObject()-method added in #251
* Description of the method.
* A simple method-calling example added to the existing example code.
> Added some documentation for AngularMeteorObject.getRawObject()

- package.js
- plugin/handler.js
> fix for #275. parse html before minifying.

- plugin/handler.js
> add js extension to compiled ng.html files

- .docs/angular-meteor/client/views/steps/tutorial.step_17.html
Match the tutorial to the layout in angular-meteor. Update some text, change some instructions.
> Updated tutorial step 17

- .docs/angular-meteor/client/views/api/api.auth.html
> Updated docs to use $state instead of $location for "AUTH_REQUIRED".

- package.json
ng-if  does not work properly on img tags in 1.3.13 and updating to angular 1.3.15 has the fix. See issue: https://github.com/angular/angular.js/issues/7183
> Update tests to work with the latest Angular version

- .docs/angular-meteor/client/views/steps/tutorial.step_08.html
Updated tutorial to use $state instead of $location for "AUTH_REQUIRED".
> Updated tutorial

- .docs/angular-meteor/client/views/steps/tutorial.intro.html
Update final version link with CSS.
> Update tutorial introduction

- modules/angular-meteor-user.js
Corrected a typo from pull request 301 as per @smoke detection
> Corrected a typo

- .docs/angular-meteor/client/views/api/api.auth.html
> Update docs to use requireValidUser()

- modules/angular-meteor-meteorCollection.js
> #299 remove $$hashkey from saved items two levels down

- .docs/angular-meteor/client/index.html
@Urigo check this out. Saw this on another site and thought it could be better than a dropdown which is less likely to be clicked.
> (site): move navbar items

- .docs/angular-meteor/client/index.html
- .docs/angular-meteor/client/styles/angular-2.less
- .docs/angular-meteor/client/views/angular-2.html
* Added buttons
* Removed more code toggle.
> Fix styles

- .docs/angular-meteor/client/views/steps/tutorial.step_18.tpl
Second attempt to see if we can automerge
> Update of Step 18 material design login

- .docs/angular-meteor/client/scripts/routes.ng.js
- .docs/angular-meteor/client/views/steps/tutorial.step_18.tpl
- .docs/angular-meteor/client/views/steps/tutorial.step_19.tpl
- .docs/angular-meteor/client/views/tutorial.html
Add part 19 to the tutorial - third-party packages.
> Add part 19 to the tutorial - third-party packages.

- README.md
Hi
I think there is a word missing in the User Auth Readme section.  Trivial change.
thanks
> trivial word addition complete -> complete support

- .docs/angular-meteor/client/views/api/api.meteorObject.html
Explanation about retrieving documents that are stored with object Ids
> mongo documents with ObjectId

- .docs/angular-meteor/client/views/steps/tutorial.step_09.tpl
I am not sure if this fix is correct - didn't know how to preview it. anyway in the original doc this part is not displayed as code, and something bad with the formatting. I tried to fix indentation.
> fix code snippet that is not displayed as code

- .docs/angular-meteor/client/views/api/api.AngularMeteorCollection.html
Added the return value for the save as discussed in https://github.com/Urigo/angular-meteor/issues/383
> Angular Meteor Collection API doc

- .docs/angular-meteor/client/views/api/api.meteorCollection.html
added explanation about stopping meteor collection
> API update

- .docs/angular-meteor/client/views/api/api.meteorCollection.html
to make it more clear and self-explaining
> rephrase a sentence

- lib/diff-array.js
- tests/integration/angular-meteor-diff-array-spec.js
Fixed a bug where different dates did not trigger an "is changed" updated.
Issue #418
> Pull request for issue #418 - Date is interpreted as an object in diff-array.js

- .docs/angular-meteor/client/views/steps/tutorial.intro.html
Hi Uri - let me know if you are ok with these changes and I'll try and update some more of the tutorial.
> grammar cleanup - tutorial intro

- modules/angular-meteor-object.js
Was referencing $meteorCollection. 
Probably a copy+paste typo.
> Small fix on error log message

- modules/angular-meteor-camera.js
> fix typo in angumar-meteor.camera

- .docs/angular-meteor/client/views/steps/tutorial.intro.html
> Fixed typo

- .docs/angular-meteor/client/views/steps/tutorial.step_00.html
moving down the steps - first part (step_00)
> tutorial docs cleanup - step_00

- lib/diff-array.js
- tests/integration/angular-meteor-diff-array-spec.js
I wrote a test that show cases the problem and a fix that seems to work
> new fields in diff-array cause undefined access error

- .docs/angular-meteor/client/views/steps/tutorial.step_09.html
service that also ``return`` -> service that also ``returns``
> Trivial grammar fix step 9

- .docs/angular-meteor/client/views/api/api.collectionfs.html
- angular-meteor.js
- lib/diff-array.js
- modules/angular-meteor-meteorCollection.js
- tests/integration/angular-meteor-diff-array-spec.js
- Added ability to override the "diffArray" of the $meteorCollection base object in case of collection with special objects (like CollectionFS).
- This PR also the solution for "Max Call Stack" errors when trying to work with CollectionFS.
> Add $meteor.collectionFS for handeling these collections

- .docs/angular-meteor/client/index.html
- .docs/angular-meteor/client/routes.ng.js
- .docs/angular-meteor/client/views/steps/tutorial.step_20.html
- .docs/angular-meteor/client/views/tutorial.html
- modules/angular-meteor-meteorCollection.js
Added $scope.$meteorCollectionFS support
> Added $scope.$meteorCollectionFS support

- .docs/angular-meteor/client/views/steps/tutorial.step_05.html
- .docs/angular-meteor/client/views/steps/tutorial.step_06.html
> tutorial docs cleanup - step_05

- lib/diff-array.js
- tests/integration/angular-meteor-diff-array-spec.js
> Fix bad behavior of diffArray on the presence of nulled and empty objects 

- .docs/angular-meteor/client/views/steps/tutorial.step_08.html
Added a disclaimer that states authentication on the client (via ui-router) can be circumvented by someone with malicious intent.
> Added disclamer to authentication

- modules/angular-meteor-utils.js
Seems like we still must use the specific code that handles FS.File on stripDollar function.
> Fix CollectionFS file upload issue

- .docs/angular-meteor/client/views/steps/tutorial.step_00.html
- .docs/angular-meteor/client/views/steps/tutorial.step_01.html
- .docs/angular-meteor/client/views/steps/tutorial.step_02.html
- .docs/angular-meteor/client/views/steps/tutorial.step_03.html
- .docs/angular-meteor/client/views/steps/tutorial.step_04.html
- .docs/angular-meteor/client/views/steps/tutorial.step_05.html
- .docs/angular-meteor/client/views/steps/tutorial.step_06.html
- .docs/angular-meteor/client/views/steps/tutorial.step_07.html
- .docs/angular-meteor/client/views/steps/tutorial.step_08.html
- .docs/angular-meteor/client/views/steps/tutorial.step_09.html
- .docs/angular-meteor/client/views/steps/tutorial.step_11.html
- .docs/angular-meteor/client/views/steps/tutorial.step_12.html
- .docs/angular-meteor/client/views/steps/tutorial.step_13.html
- .docs/angular-meteor/client/views/steps/tutorial.step_14.html
- .docs/angular-meteor/client/views/steps/tutorial.step_15.html
- .docs/angular-meteor/client/views/steps/tutorial.step_16.html
- .docs/angular-meteor/client/views/steps/tutorial.step_17.html
- .docs/angular-meteor/client/views/steps/tutorial.step_19.html
Fixed wording, typos and added Markdown backtick quotes where missing.
> Update tutorial steps 00 through 19

- .docs/angular-meteor/client/views/steps/tutorial.step_18.html
In ResetCtrl the function was mistakenly named register instead of reset. This does'n match the following template code which expects the name to be reset
> Fix ResetCtrl function name, some typos

- .docs/angular-meteor/client/views/steps/tutorial.step_09.html
IMHO "permissions sent to the client" sounds a little odd and a google search confirms that it's not a common idiom.  Perhaps "data sent to the client" is more appropriate.
> Update tutorial.step_09.html, trivial word re-order

- .docs/angular-meteor/client/views/steps/tutorial.step_12.html
``directive`` -> ``directives``
> Update tutorial.step_12.html, trivial plural change

- .docs/angular-meteor/client/views/api/api.meteorCollection.html
> Update api.meteorCollection.html (Typo)

- .docs/angular-meteor/client/views/steps/tutorial.step_09.html
> Update tutorial.step_09.html (Typo)

- .docs/angular-meteor/client/views/api/api.AngularMeteorCollection.html
> Update api.AngularMeteorCollection.html (Typo)

- .docs/angular-meteor/client/routes.ng.js
- .docs/angular-meteor/client/views/api.html
- .docs/angular-meteor/client/views/api/api.ngFileExtension.html
- .docs/angular-meteor/public/sitemap.xml
That info needs to be in the docs too - not only hidden away in the tutorial ;)
> Added a section to the docs for the ng.js and ng.html file extensions

- .docs/angular-meteor/client/views/steps/tutorial.step_18.html
The path to `app.js` is incorrect
> Fix path to app.js

- examples/performance/.meteor/versions
- modules/angular-meteor-meteorCollection.js
- tests/integration/angular-meteor-collection-spec.js
Hi,
In order to simplify adding further improvements and as a part of road to 1.0 version, I thought why not to brush/overview collection module which basically means removing unnecessary code, making some code logically clearer, minor improvements plus refined code style rules.
Some new tests are also added.
I tried to test it well and did mostly with the help of the to-do demo app.
Your comments are welcome. If you are not ok with some changes, we can discuss leaving only ones that really needed.
> Clean-up/re-factoring of the collection module plus some small improvements plus new tests

- .docs/angular-meteor/client/content/tutorials/angular2/md/00.md
- .docs/angular-meteor/client/content/tutorials/angular2/md/01.md
- .docs/angular-meteor/client/content/tutorials/angular2/md/02.md
- .docs/angular-meteor/client/content/tutorials/angular2/md/03.md
- .docs/angular-meteor/client/content/tutorials/angular2/md/04.md
- .docs/angular-meteor/client/content/tutorials/angular2/md/05.md
- .docs/angular-meteor/client/content/tutorials/angular2/md/06.md
- .docs/angular-meteor/client/content/tutorials/angular2/tutorial.step_00.html
- .docs/angular-meteor/client/content/tutorials/angular2/tutorial.step_01.html
- .docs/angular-meteor/client/content/tutorials/angular2/tutorial.step_02.html
- .docs/angular-meteor/client/content/tutorials/angular2/tutorial.step_03.html
- .docs/angular-meteor/client/content/tutorials/angular2/tutorial.step_04.html
- .docs/angular-meteor/client/content/tutorials/angular2/tutorial.step_05.html
Steps 00 -> 05 written in markdown & html.
> Angular 2 tutorial steps 00 to 05

- .dist/BUNDLE.md
- .dist/bundle-min.sh
- .gitignore
- README.md
- bower.json
* Create bundle and minified file with the meteor dependencies
* Add angular as bower dependency
* Add meteor-client-side as bower dependency
> Add bundle-minified script and update bower dependencies

- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorial.step_00.html
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorial.step_02.html
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorial.step_03.html
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorial.step_05.html
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorial.step_06.html
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorial.step_07.html
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorial.step_08.html
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorial.step_09.html
- formatting
- broken link
- a few typos
> Angular 2 tutorial minor fixes

- lib/diff-array.js
- lib/get-updates.js
- modules/angular-meteor-meteorCollection.js
- modules/angular-meteor-object.js
- modules/angular-meteor-stopper.js
- package.js
- tests/integration/angular-meteor-diff-array-spec.js
- General refactor for collection and object
- Fix some code duplications
- Add $meteorBound for easy scope binding to meteor entities
- Update necessary object properties on change
> refactor object and collection

- modules/angular-meteor-collection.js
- tests/integration/angular-meteor-collection-spec.js
Removes async tests since they are not needed.
Adds one test to test removing all docs.
Deployed along with ToDo app here http://ng-to-do-test.meteor.com
> Corrects prev changes that didn't get into the code base.

- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_06.html
- Remove useless Meteor.isClient test because we are in client directory and remove too many closing braces at the end
- Make router-link '/parties-list' homogeneous with the beginning of document
> Minor fixes in tutorialAngular2.step_06.html

- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_07.html
The modified part is not very clear. I propose to put the complete code to avoid any mistake.
> Part not very clear

- README.md
Just a small addition to the readme to encourage people to contribute to the documentation :)
> Add instructions on how to contribute to documentation

- .docs/angular-meteor/client/home/home.html
- .docs/angular-meteor/client/layout/layout.html
- .docs/angular-meteor/client/layout/navbar.html
- .docs/angular-meteor/client/stylesheets/home/home.import.less
- .docs/angular-meteor/client/stylesheets/main.less
* Bring some things above the fold
* Add link to submit
* Move around front page elements
* Add Open Source Meta Tags (cc @RichardLitt)
* Going to explore some new designs for the visual thingies
* Clean up some of the text on certain sections of the documentation. Paragraph width, etc.
> Initial tweaks to website

- README.md
I ran `doctoc` on README.md and it generated the table of content.
> Added table of content to Readme.md

- .docs/angular-meteor/client/layout/navbar.html
- .docs/angular-meteor/client/stylesheets/content/api_tutorial/code_styles.import.less
- .docs/angular-meteor/client/stylesheets/content/api_tutorial/common.import.less
- .docs/angular-meteor/client/stylesheets/content/api_tutorial/tutorial.import.less
- .docs/angular-meteor/client/stylesheets/home/home.import.less
- .docs/angular-meteor/client/stylesheets/main.less
* Added step 21 to the tutorials dropdown
* Fixed some padding and width things.
> Website style updates

- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_00.md
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_01.md
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_02.md
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_03.md
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_04.md
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_05.md
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_06.md
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_07.md
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_08.md
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_09.md
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_10.md
Preparing for refactor into new tutorial system. 
Step 1: Move content into stubailo/meteor-markdown-templating.
> Changed tutorial steps to use meteor-markdown-templating

- .docs/angular-meteor/client/content/patches/angular-meteor.multi.patch
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_20.md
> Added new patch file.

- README.md
Thanks for your works. It's just a mistake.
> brackets mistake

- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_11.md
Changed "If your application does not works" to "If your application does not work".
> Small typo

- .docs/angular-meteor/client/content/patches/angular-meteor.multi.patch
@Urigo 
Fixes https://github.com/Urigo/meteor-angular-socially/issues/54
> Fixed typo in Step 12

- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_12.md
Ironing out some minor issues.
> Some Grammar naziing

- .docs/angular-meteor/client/content/patches/angular2-meteor.multi.patch
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_09.md
Step 9 updated
Step 10 (already complete)
> Complete conversion of angular2 tutorial to use new tutorial

- .docs/angular-meteor/client/content/patches/angular2-meteor.multi.patch
Minor change. Incorrect step number.
> angular2 tutorial patch: rename step 8.2 -> 8.1

- .docs/angular-meteor/client/content/tutorials/tutorial-intro.html
- .docs/angular-meteor/client/stylesheets/content/api_tutorial/common.import.less
- .docs/angular-meteor/client/stylesheets/content/api_tutorial/tutorial.import.less
Some small fixes to make spacing more consistent in the docs.
> Fix some spacing things

- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_09.md
Improved phrasing of how to move subscriptions to your routing.js file.
> Fix phrasing

- .docs/angular-meteor/client/content/api/api.AngularMeteorCollection.html
$scope.$meteorCollection().Subscribe() gets publisher arguments
https://github.com/Urigo/angular-meteor/issues/735
> add arguments to collection.subscribe()

- lib/get-updates.js
- modules/angular-meteor-object.js
- tests/integration/angular-meteor-get-updates-spec.js
- tests/integration/angular-meteor-object-spec.js
> bugfix (get-updates): changed the way array changes are saved to mongo.

- .docs/angular-meteor/client/content/api/api.AngularMeteorCollection.html
Typo corrected, as suggested earlier on @TallyB PR
> Typo correction

- .docs/angular-meteor/client/content/patches/angular2-tutorial.multi.patch
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_00.md
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_01.md
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_02.md
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_03.md
- .docs/angular-meteor/client/layout/stepbar.js
- .docs/angular-meteor/client/lib/tutorials_register.js
- .docs/angular-meteor/packages/tutorial-step-diff-compiler/plugin.js
Update 4 steps of the Angular2 tutorial to be consistent the new Angular2-Meteor package.
Forth step is only half ready.
Deployed here - http://ng-meteor.meteor.com.
> Angular2 Tutorial

- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_00.md
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_02.md
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_03.md
- .docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_04.md
Mostly typos/clarifications/file destinations.
> ng2-tutorial: step00 markdown edits

- .docs/angular-meteor/client/content/patches/angular-meteor.multi.patch
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_02.md
> Updates for the tutorial after updating the Angular di issue

- .docs/angular-meteor/client/content/patches/ionic-tutorial.multi.patch
- .docs/angular-meteor/client/content/tutorials/ionic/steps/ionic.step_01.md
- .docs/angular-meteor/client/content/tutorials/ionic/steps/ionic.step_02.md
- .docs/angular-meteor/client/content/tutorials/ionic/steps/ionic.step_03.md
- .docs/angular-meteor/client/content/tutorials/ionic/steps/ionic.step_04.md
- .docs/angular-meteor/client/content/tutorials/ionic/steps/ionic.step_05.md
- .docs/angular-meteor/client/content/tutorials/ionic/steps/ionic.step_06.md
> Update steps numbers to match the new patch file 

- .docs/angular-meteor/client/content/patches/angular-meteor.multi.patch
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_03.md
@Urigo 
Closes this:
https://github.com/Urigo/angular-meteor/issues/778
> Update tutorial after some fixes in step 3

- .docs/angular-meteor/public/sitemap.xml
Update site map with ionic tutorial
@Urigo
> Update site map with ionic tutorial

- lib/get-updates.js
- tests/integration/angular-meteor-get-updates-spec.js
Discovered that updates were storing what should be an array as an object. 
Added test and got the test to pass.
Also fixed a couple of tests that were failing only because the expectation was set incorrectly I believe.
> Updates with $push for new subarrays (just kidding)

- modules/angular-meteor-object.js
- tests/integration/angular-meteor-object-spec.js
In continues to pull request #794.
> Fix callback invoked too early on meteorObject.save()

- .docs/angular-meteor/client/content/tutorials/ionic/steps/ionic.step_04.md
- .docs/angular-meteor/client/content/tutorials/ionic/steps/ionic.step_05.md
- .docs/angular-meteor/client/content/tutorials/ionic/steps/ionic.step_06.md
- .docs/angular-meteor/packages/tutorial-step-diff-compiler/.npm/plugin/mdg:tutorial-step-diffs-plugin/npm-shrinkwrap.json
I found some errors with the snippets, so i fixed to avoid future confusions.
> Fixed ionic tutorial chapters: 4,5,6

- .docs/angular-meteor/client/content/tutorials/tutorial-intro.html
- .docs/angular-meteor/client/layout/sidebar.js
- .docs/angular-meteor/client/layout/stepbar.js
@Urigo 
After adding step 22 - there is a bug with the routes because of the name of the tutorial.
> Fixes for routes detection

- .docs/angular-meteor/client/content/patches/angular-meteor.multi.patch
@Urigo 
After fixing these: 
https://github.com/Urigo/meteor-angular-socially/issues/79#issuecomment-152686480
https://github.com/Urigo/meteor-angular-socially/issues/80
> Update patch file after updating socially code

- .docs/angular-meteor/client/content/patches/angular-meteor.multi.patch
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_00.md
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_01.md
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_02.md
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_03.md
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_05.md
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_06.md
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_07.md
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_08.md
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_09.md
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_12.md
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_13.md
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_14.md
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_15.md
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_16.md
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_18.md
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_20.md
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_21.md
- .docs/angular-meteor/client/content/tutorials/angular1/steps/tutorial.step_22.md
> Update PATCH file and steps using angular-meteor 1.2

- packages/angular-meteor-data/tests/integration/angular-meteor-diff-array-spec.js
As described here https://github.com/Urigo/angular-meteor/pull/836/files#r44182491
> Fix assert .not.toHaveBeenCalled()

- modules/angular-meteor-collection.js
- modules/angular-meteor-object.js
- tests/integration/angular-meteor-collection-spec.js
- tests/integration/angular-meteor-object-spec.js
Now any splice operation can be done without receiving any errors, both for object and collection
> Fix angular-meteor splice

- docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_03.md
- docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_04.md
- docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_05.md
- docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_06.md
- docs/angular-meteor/client/content/tutorials/patches/meteor-angular2-socially.multi.patch
1. Rearranges substeps of the 3rd step to define collection on the server side before inserts from the mongo terminal (#806, #7)
2. Fixes some minor issues: global zone replaced to the specific Angular 2 one, explanation for 'angular2/router' added
3. Revision of Step 06
Deployed - http://ng2-tutorial.meteor.com
> Ng2 Tutorial Updates

- docs/angular-meteor/client/content/tutorials/angular2/steps/tutorialAngular2.step_03.md
Having followed the Angular 2 tutorial the `app.ts` file differs to what the documentation suggests it should be at this stage. Issue #847
> Fix step3 docs

- packages/angular-meteor-data/angular-meteor.js
> (bug) Fixed strict di issue with $delegate

- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_07.md
- docs/angular-meteor/client/content/tutorials/socially/patches/meteor-angular2-socially.multi.patch
Deployed - http://ng2-tutorial.meteor.com/tutorials/socially/angular2/folder-structure
> Revision of the Step 7 for Angular 2

- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_00.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_08.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_09.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_10.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_11.md
Adds 11th step and minor corrections/updates to some previous steps.
Fixes https://github.com/barbatus/ng2-meteor-accounts/issues/1
Deployed - ng2-tutorial.meteor.com
> Angular2 Tutorial Updates

- packages/angular-meteor-data/modules/angular-meteor-reactive-context.js
- Refactor reactive context module
- Fix tests and make necessary changes
- Helpers initialization order is set by decleration order
> 1.3 refactor fix

- packages/angular-meteor-data/modules/angular-meteor-user.js
> Correct deprecated messages

- packages/angular-meteor-data/angular-meteor.js
- packages/angular-templates/package.js
- packages/angular-templates/templates-handler.js
> (feat) Move templates handle to the angular-meteor-templates

- docs/angular-meteor/client/content/tutorials/socially/patches/meteor-angular1-socially.multi.patch
> (bug) Fix socially step 16 (Google Maps) and update the PATCH file

- packages/angular-meteor-data/modules/angular-meteor-camera.js
- packages/angular-meteor-data/modules/angular-meteor-collection.js
- packages/angular-meteor-data/modules/angular-meteor-methods.js
- packages/angular-meteor-data/modules/angular-meteor-object.js
- packages/angular-meteor-data/modules/angular-meteor-session.js
- packages/angular-meteor-data/modules/angular-meteor-subscribe.js
- packages/angular-meteor-data/modules/angular-meteor-user.js
- packages/angular-meteor-data/modules/angular-meteor-utils.js
> Fixed spelling error: "sine" -> "since"

- docs/angular-meteor/client/content/tutorials/socially/angular1/tutorials.socially.angular1.step_14.md
- docs/angular-meteor/client/content/tutorials/socially/angular1/tutorials.socially.angular1.step_15.md
> Fix step 15

- packages/angular-meteor-data/modules/angular-meteor-reactive-context.js
- packages/angular-meteor-data/tests/integration/angular-meteor-reactive-context.spec.js
> Idanwe bug/scope with helper name

- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_02.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_03.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_04.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_05.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_06.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_08.md
- docs/angular-meteor/client/content/tutorials/socially/patches/meteor-angular2-socially.multi.patch
Updates tutorial with the new Angular2 version changes, plus adds some minor corrections and new changes.
Fixes https://github.com/Urigo/meteor-angular2.0-socially/issues/18.
Deployed at ng2-tutorial.meteor.com.
> Updates tutorials

- packages/angular-meteor-data/modules/angular-meteor-reactive-context.js
@Urigo needed fix for a bug I had in 3rdfriday.
> bugfix (reactive):  digest scope when helper property is changed.

- docs/angular-meteor/client/content/api-reference/1.2.2/api.auth.html
- packages/angular-meteor-data/modules/angular-meteor-user.js
Remove redundant $utils deprecation message from angular-meteor-user and add it's own message
> angular-meteor-user(deprecation message): Remove redundant deprecation message #945

- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_00.md
I'll submit more as I complete the tutorial 😁
> Minor grammar/English improvements

- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_07.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_08.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_10.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_11.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_12.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_13.md
- docs/angular-meteor/client/content/tutorials/socially/patches/meteor-angular2-socially.multi.patch
Adds step 13th, mirror corrections to the previous steps.
Deployed - ng2-tutorial.meteor.com
> Angular2 Tutorial: step 13th

- docs/angular-meteor/both/router/router.js
- docs/angular-meteor/client/content/tutorials/socially/angular1/tutorials.socially.angular1.step_12.md
- docs/angular-meteor/client/content/tutorials/socially/patches/meteor-angular1-socially.multi.patch
> Docs/update after 1.3.1 changes

- docs/angular-meteor/client/content/api-reference/1.3.1/api.ngFileExtension.html
> Grammar Correction

- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_03.md
While trying the tutorial, I had to adjust the mongodb statement.
I hope, this is the correct branch to make pull requests to.
> Added ObjectId reference for db entry removal.

- docs/angular-meteor/client/content/api-reference/1.3.2/api.auth.html
Fix the description regarding where the service is implemented and how to add it to the project.
> fix angular-meteor-auth adding instructions

- packages/angular-meteor-auth/modules/auth.js
> auth.js doesn't pass minification

- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_01.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_02.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_03.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_04.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_05.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_06.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_07.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_08.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_09.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_12.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_13.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_14.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_15.md
- docs/angular-meteor/client/content/tutorials/socially/patches/meteor-angular2-socially.multi.patch
Add some notes to the 12th, 14th steps, minor corrections to the 15th step.
Fixes https://github.com/Urigo/angular2-meteor/issues/52, https://github.com/Urigo/meteor-angular2.0-socially/issues/23.
> Angular 2 Tutorial Updates

- docs/angular-meteor/client/content/api-reference/1.3.1/api.helpers.html
> Syntax Correction

- docs/angular-meteor/client/content/angular-2/angular-2.html
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_02.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_03.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_04.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_05.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_06.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_08.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_09.md
- docs/angular-meteor/client/content/tutorials/socially/patches/meteor-angular2-socially.multi.patch
ngFor, ngIf etc are globally available in Angular 2.
Deployed - http://ng2-tutorial.meteor.com
> Angular 2 Tutorial Updates: fixes outdated syntax in multiple steps.

- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_00.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_02.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_03.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_04.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_05.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_06.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_07.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_08.md
@barbatus 
Tutorial changes:
* wording (clarifications, typos, etc.)
* additional links to docs (Angular.io, Meteor Docs, Mongo Docs)
No code changes.
> Ng2 Tutorial Edits

- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_00.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_02.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_03.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_13.md
fix broken list in step 13
remove references to extending interfaces in step 13
add spaces under titles for consistency.
> ng2 tutorial: 

- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_13.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_14.md
Only text edits, no code changes.
Specified capital M for Methods, to avoid confusion with Javascript methods.
> ng2 tutorial step14 edits

- packages/angular-meteor-auth/modules/auth.js
- packages/angular-meteor-auth/package.js
- packages/angular-meteor-auth/tests/integration/auth.spec.js
- packages/angular-meteor-auth/tests/test_collections.js
- packages/angular-meteor-auth/tests/test_mocks.js
Auth:
- Add tests
- Stop autorun once promises have been fulfilled
- Add method for manual autorun stopping
- Refactor
- Fix bugs
> Stop fulfilled auth promises, add manual stop and extend tests

- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_15.md
Rephrasing for clarity, typos, etc. No code edits.
> ng2 tutorial step15 edits

- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_00.md
- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_21.md
- docs/angular-meteor/client/content/tutorials/socially/patches/meteor-angular2-socially.multi.patch
Deployed - ng2-tutorial.meteor.com
> Step 21th added

- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_09.md
typo: change queryBuild.call to buildQuery.call in the tutorial
> change queryBuild.call to buildQuery.call

- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_00.md
Change `angular2/bootstrap` to `angular2/platform/browser`.
If use `angular2/bootstrap`, the page will show blank.
> Update to angular2/platform/browser

- packages/angular-meteor-data/modules/angular-meteor-reactive-context.js
- packages/angular-meteor-data/modules/angular-meteor-reactive-scope.js
- packages/angular-meteor-data/tests/integration/angular-meteor-reactive-context.spec.js
- packages/angular-meteor-data/tests/integration/angular-meteor-reactive-scope.spec.js
This PR implements `getCollectionReactively()`. I tried to do it in as clean a manner as possible, but let me know if you have any suggestions for improving anything, and I will be happy to make those adjustments.
Fixes #1088
> Add getCollectionReactively()

- docs/angular-meteor/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_16.md
Add typings/ng2-google-maps/ng2-google-maps.d.ts
> Add typings/ng2-google-maps/ng2-google-maps.d.ts

- packages/angular-meteor-data/tests/integration/reactive.spec.js
Cleanup a couple of the `reactivateCollection` tests added in #1165.
> Cleanup reactivate collection

- docs/angular-meteor/client/content/tutorials/socially/angular1/tutorials.socially.angular1.step_21.md
Add clarity about using package prefix in meteor package name and absolute paths elsewhere in the
application which reference the package
References #958
> docs: explain package prefix with absolute path

- .travis.yml
- packages/angular-meteor-data/angular-meteor.js
- packages/angular-meteor-data/modules/angular-meteor-camera.js
- packages/angular-meteor-data/modules/angular-meteor-collection.js
- packages/angular-meteor-data/modules/angular-meteor-methods.js
- packages/angular-meteor-data/modules/angular-meteor-object.js
- packages/angular-meteor-data/modules/angular-meteor-session.js
- packages/angular-meteor-data/modules/angular-meteor-settings.js
- packages/angular-meteor-data/modules/angular-meteor-subscribe.js
- packages/angular-meteor-data/modules/angular-meteor-user.js
- packages/angular-meteor-data/modules/angular-meteor-utils.js
- packages/angular-meteor-data/modules/reactive.js
- packages/angular-meteor-data/package.js
> fix($angularMeteorSettings): unknown provider

- .github/ISSUE_TEMPLATE.md
> Fixed grammar

- dist/angular-meteor.js
- src/modules/angular-meteor-utils.js
- tests/integration/pre1.3/angular-meteor-collection-spec.js
- tests/package.js
> fix: Legacy modules tests not passing

- dist/angular-meteor.js
- src/modules/mixer.js
- src/modules/scope.js
- tests/integration/mixer.spec.js
> fix: Apply mixins to rootScope

- docs/angular-meteor/client/content/api-reference/angular1-meteor/1.3.6/api.auth.html
> docs(auth): Update auth docs to match fixes

- docs/angular-meteor/client/content/tutorials/socially/angular1/tutorials.socially.angular1.step_09.md
> docs(tutorial): Fix typo in angular1 tutorial

- dist/angular-meteor.js
- src/modules/core.js
- src/modules/mixer.js
- src/modules/reactive.js
- src/modules/utils.js
- src/modules/view-model.js
- tests/integration/reactive.spec.js
- tests/integration/view-model.spec.js
> fix(viewmodel): View model and scope can both use 'getReactively'

- package.json
- webpack/common.js
> fix: missing dependencies in npm

- src/modules/angular-meteor-settings.js
To stop showing warnings by default.
> feat($angularMeteorSettings): suppress warnings

- scripts/dev.js
Reproduction:
```bash
npm run dev:stop
npm run dev:stop
```
Before:
```javascript
// angular-meteor-data/package.js
api.add_files([
'.npm/package/node_modules/angular-meteor/dist/angular-meteor.js.npm/package/node_modules/angular-meteor/dist/angular-meteor.js'
], 'client', {
transpile: false
});
```
After:
```javascript
// angular-meteor-data/package.js
api.add_files([
'.npm/package/node_modules/angular-meteor/dist/angular-meteor.js'
], 'client', {
transpile: false
});
```
> chore: improve patterns in scripts/dev

- bundle-min.sh
This reverts commit a98b2cf22f155da0543812c0e881d0303e1e319b.
> Revert "chore(bundle): Add modules package to bundle script"

- packages/angular-templates-runtime/package.js
> Remove cheerio from npm dependencies

- packages/angular-templates/templates-handler.js
> fix(angular-templates): forward slash breaking change

- packages/angular-templates/README.md
- packages/angular-templates/package.js
> docs(angular-templates): add README

- packages/angular-templates/plugin.js
Fixes #1410 
Repo to test things: https://github.com/kamilkisiela/angular-templates-test
> fix(angular-templates): missing lazy-loading for non imports dirs

- packages/angular2-meteor/README.md
- packages/angular2-meteor/modules/providers.ts
Reverts Urigo/angular-meteor#1430
> Revert "Add back IterableDiffers issue's workaround"

- packages/angular2-meteor/atmosphere-packages/css-compiler/compilers/basic_compiler.js
- packages/angular2-meteor/atmosphere-packages/css-compiler/package.js
As described in https://github.com/Urigo/angular2-meteor/issues/396
> fix(css-compiler): escape css output

- packages/angular2-meteor/atmosphere-packages/angular2-with-blaze-compilers/package.js
- packages/angular2-meteor/atmosphere-packages/angular2-with-blaze-compilers/plugin/register.js
@Urigo 
Merge and publish new version only after: https://github.com/Urigo/angular-meteor/pull/1462
> chore(blaze-compiler): Updated version and dependencies

- packages/angular2-meteor/atmosphere-packages/angular2-compilers/package.js
- packages/angular2-meteor/atmosphere-packages/css-compiler/compilers/basic_compiler.js
- packages/angular2-meteor/atmosphere-packages/css-compiler/package.js
- packages/angular2-meteor/examples/todos-meteor-1.3/client/app.component.ts
https://github.com/Urigo/angular2-meteor/issues/427
> Fix issue in the style compiler for the deployment

- package.json
https://greenkeeper.io/
Before you submit a pull request, please make sure you have to following:
> chore(package): update zone.js to version 0.7.4

- renovate.json
Reverting renovate ignore path thanks to @rarkins adding it to renovate!
> chore(dependencies): Reverting renovate ignore

- README.md
> docs(badges): Update build badges to the new structure

- .travis.yml
- examples/angularcli-meteor/e2e/app.e2e-spec.ts
- examples/angularcli-meteor/e2e/app.po.ts
- run_tests.sh
Before you submit a pull request, please make sure you have to following:
> Add tests for angularcli-meteor

- atmosphere-packages/angular-typescript-compiler/package.js
- examples/MeteorCLI/all-in-one/package.json
- examples/MeteorCLI/lazy-loading/package.json
- examples/MeteorCLI/universal/package.json
- examples/angularcli-meteor/package-lock.json
- examples/angularcli-meteor/package.json
Reverts Urigo/angular-meteor#1720
> Revert "chore(deps): update dependency typescript to v2.6.1"

- atmosphere-packages/angular-compilers/.versions
- atmosphere-packages/angular-compilers/package.js
- atmosphere-packages/angular-html-compiler/index.js
- atmosphere-packages/angular-scss-compiler/index.js
- atmosphere-packages/angular-typescript-compiler/.versions
- atmosphere-packages/angular-typescript-compiler/index.js
- atmosphere-packages/angular-typescript-compiler/package.js
- examples/MeteorCLI/lazy-loading/package-lock.json
- examples/MeteorCLI/lazy-loading/package.json
- examples/angularcli-meteor/package-lock.json
- tests/angular-compilers-tests/.meteor/versions
In the new version,
- Seperated log messages of compilation stages
- Fixed Issues about asset compilation
> publish new version of compilers

- atmosphere-packages/angular-compilers/.versions
- atmosphere-packages/angular-compilers/package.js
- atmosphere-packages/angular-typescript-compiler/.versions
- atmosphere-packages/angular-typescript-compiler/index.js
- atmosphere-packages/angular-typescript-compiler/package.js
This PR fixes;
https://github.com/Urigo/angular-meteor/issues/1789
https://github.com/Urigo/angular-meteor/issues/1790
> [fix] Exclude modules and tsConfig parse problem

- .travis.yml
- run_tests.sh
Travis CI needs google-chrome packages to be added in .travis.yml file.
> Fix tests by adding google-chrome package

- .github/ISSUE_TEMPLATE.md
This just makes some links work. No big deal.
> Fix links to "feature requests" and "reporting a bug"
